export const locations = [
  "USA",
  "Canada",
  "Argentina",
  "Antigua and Barbuda",
  "Uruguay",
  "Ecuador",
  "El Salvador",
  "Guyana",
  "Cuba",
  "Guatemala",
  "Grenada",
  "Costa Rica",
  "Colombia",
  "Jamaica",
  "Suriname",
  "St. Vincent and the Grenadines",
  "St. Christopher and Nevis",
  "Saint Lucia",
  "Chile",
  "Dominica",
  "Dominican Republic",
  "Trinidad and Tobago",
  "Nicaragua",
  "Haiti",
  "Panama",
  "Bahamas",
  "Paraguay",
  "Barbados",
  "Brazil",
  "Venezuela",
  "Belize",
  "Peru",
  "Bolivia",
  "Honduras",
  "Mexico",
  "India",
  "Indonesia",
  "Cambodia",
  "Singapore",
  "Sri Lanka",
  "Thailand",
  "South Korea",
  "China",
  "Nepal",
  "Pakistan",
  "Bangladesh",
  "Timor-Leste",
  "Philippines",
  "Bhutan",
  "Brunei",
  "Vietnam",
  "Malaysia",
  "Myanmar",
  "Maldives",
  "Mongolia",
  "Laos",
  "North Korea",
  "Hong Kong",
  "Taiwan",
  "Macau",
  "Japan",
  "Australia",
  "Kiribati",
  "Cook Islands",
  "Samoa",
  "Solomon Islands",
  "Tuvalu",
  "Tonga",
  "Nauru",
  "Niue",
  "New Zealand",
  "Vanuatu",
  "Papua New Guinea",
  "Palau",
  "Fiji",
  "Marshall Islands",
  "Micronesia",
  "Afghanistan",
  "United Arab Emirates",
  "Yemen",
  "Israel",
  "Iraq",
  "Iran",
  "Oman",
  "Qatar",
  "Kuwait",
  "Saudi Arabia",
  "Syria",
  "Turkey",
  "Bahrain",
  "Jordan",
  "Lebanon",
  "Palestine",
  "Iceland",
  "Ireland",
  "Azerbaijan",
  "Albania",
  "Armenia",
  "Andorra",
  "Italy",
  "Ukraine",
  "Uzbekistan",
  "United Kingdom",
  "Estonia",
  "Austria",
  "Netherlands",
  "Kazakhstan",
  "Cyprus",
  "Greece",
  "Kyrgyzstan",
  "Croatia",
  "Kosovo",
  "San Marino",
  "Georgia",
  "Switzerland",
  "Sweden",
  "Spain",
  "Slovakia",
  "Slovenia",
  "Serbia",
  "Tajikistan",
  "Tchech Republic",
  "Denmark",
  "Germany",
  "Turkmenistan",
  "Norway",
  "Vatican",
  "Hungary",
  "Finland",
  "France",
  "Bulgaria",
  "Belarus",
  "Belgium",
  "Poland",
  "Bosnia and Herzegovina",
  "Portugal",
  "Macedonia",
  "Malta",
  "Monaco",
  "Moldova",
  "Montenegro",
  "Latvia",
  "Liechtenstein",
  "Lithuania",
  "Romania",
  "Luxembourg",
  "Russia",
  "Algeria",
  "Angola",
  "Uganda",
  "Egypt",
  "Ethiopia",
  "Eritrea",
  "Ghana",
  "Cabo Verde",
  "Gabon",
  "Cameroon",
  "Gambia",
  "Guinea",
  "Guinea-Bissau",
  "Kenya",
  "Ivory Coast",
  "Comoros",
  "Congo Republic",
  "DR Congo",
  "Sao Tome and Principe",
  "Zambia",
  "Sierra Leone",
  "Djibouti",
  "Zimbabwe",
  "Sudan",
  "Swaziland",
  "The Seychelles",
  "Equatorial Guinea",
  "Senegal",
  "Somalia",
  "Tanzania",
  "Chad",
  "Central African Republic",
  "Tunisia",
  "Togo",
  "Nigeria",
  "Namibia",
  "Niger",
  "Burkina Faso",
  "Burundi",
  "Benin",
  "Botswana",
  "Madagascar",
  "Malawi",
  "Mali",
  "South Africa",
  "South Sudan",
  "Mozambique",
  "Mauritius",
  "Mauritania",
  "Morocco",
  "Libya",
  "Liberia",
  "Rwanda",
  "Lesotho",
  "Neptune",
  "Mars",
  "Venus",
  "Mercury",
  "Earth",
  "Uranus",
  "Saturn",
  "Jupiter",
  "Pluto",
  "Moon",
  "The Bunker",
  "City Ruins",
  "Resistance Camp",
  "Abandoned Factory",
  "Desert Area",
  "Amusement Park",
  "Pascal's Village",
  "Flooded City",
  "Forest Castle",
  "Copied City",
  "The Tower",
  "The Aerie",
  "Forest of Myth",
  "Seafront",
  "Facade",
  "Shinjuku",
  "Atlantis",
  "Avalon",
  "Penglai",
  "Mag Mell",
  "Valhalla",
  "Nirai Kanai",
  "Helheim",
  "Paradise",
  "Utopia",
  "Mu",
  "Heavenly Plains",
  "The First Dimension",
  "The Second Dimension",
  "The Third Dimension",
  "The Fourth Dimension",
  "A Parallel World",
  "Heaven",
  "Hell",
];
